<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.9" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Class1.cs" />
      <Compile Remove="Dtos\**" />
      <Compile Include="DTOs\Patient\CreatePatientDto.cs" />
      <Compile Include="DTOs\Patient\PatientResponseDto.cs" />
      <Compile Include="DTOs\Patient\UpdatePatientDto.cs" />
      <Compile Remove="DTOs\Request\**" />
      <Compile Include="DTOs\SurgeryData\CreateSurgeryDataDto.cs" />
      <Compile Include="DTOs\SurgeryData\SurgeryDataResponseDto.cs" />
      <Compile Include="DTOs\SurgeryData\UpdateSurgeryDataDto.cs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
      <ProjectReference Include="..\Infra\Infra.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Dtos\**" />
      <EmbeddedResource Remove="DTOs\Request\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Dtos\**" />
      <None Remove="DTOs\Request\**" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="DTOs\.DS_Store" />
    </ItemGroup>

</Project>
