// <auto-generated />
using System;
using Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(EndoMetricsContext))]
    [Migration("20260518020136_addPatientAndSurgeryData")]
    partial class addPatientAndSurgeryData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicalRecordNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SurgeryData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("InfertilityYears")
                        .HasColumnType("int");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("PreviousPregnancy")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("SurgeryDatas", (string)null);
                });

            modelBuilder.Entity("SurgeryData", b =>
                {
                    b.HasOne("Domain.Models.Patient", null)
                        .WithOne("SurgeryData")
                        .HasForeignKey("SurgeryData", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AfsScore", "AfsScore", b1 =>
                        {
                            b1.Property<string>("SurgeryDataId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("EndometriosisScore")
                                .HasColumnType("int")
                                .HasColumnName("Afs_Endometriosis");

                            b1.Property<int>("TotalScore")
                                .HasColumnType("int")
                                .HasColumnName("Afs_Total");

                            b1.HasKey("SurgeryDataId");

                            b1.ToTable("SurgeryDatas");

                            b1.WithOwner()
                                .HasForeignKey("SurgeryDataId");
                        });

                    b.OwnsOne("SurgicalFindings", "SurgicalFindings", b1 =>
                        {
                            b1.Property<string>("SurgeryDataId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("FimbriaScore")
                                .HasColumnType("int")
                                .HasColumnName("SurgicalFindings_Fimbria");

                            b1.Property<int>("OvaryScore")
                                .HasColumnType("int")
                                .HasColumnName("SurgicalFindings_Ovary");

                            b1.HasKey("SurgeryDataId");

                            b1.ToTable("SurgeryDatas");

                            b1.WithOwner()
                                .HasForeignKey("SurgeryDataId");
                        });

                    b.Navigation("AfsScore")
                        .IsRequired();

                    b.Navigation("SurgicalFindings")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Patient", b =>
                {
                    b.Navigation("SurgeryData");
                });
#pragma warning restore 612, 618
        }
    }
}
